FROM golang
MAINTAINER foyon 
WORKDIR /Users/fanhongyi/coding/train/interview/dktest/fan 
ADD . /Users/fanhongyi/coding/train/interview/dktest/fan
RUN go build .
EXPOSE 8080
ENTRYPOINT ["./main"]
#CMD ["/bin/bash", "/go/src/script/build.sh"]
