FROM golang:latest
MAINTAINER "foyon"
WORKDIR /Users/fanhongyi/coding/train/interview/dktest/hellodocker 
ADD . /Users/fanhongyi/coding/train/interview/dktest/hellodocker 
RUN go build .
EXPOSE 8080
ENTRYPOINT ["./hellodocker"]
